/*
# Create daily_logs table

1. New Tables
- `daily_logs` — stores per-user daily emotional wellness entries.
  - `id` BIGINT identity primary key.
  - `user_id` UUID, references auth.users, cascades on delete, defaults to the authenticated user.
  - `date` DATE — the calendar day the entry represents.
  - `sleep` NUMERIC(3,1) — hours slept, constrained 0–12.
  - `stress` NUMERIC(3,1) — stress level, constrained 0–10.
  - `mood` NUMERIC(3,1) — mood level, constrained 0–10.
  - `trigger_category` TEXT — one of Work, Family, Health, Finance, None.
  - `is_baseline` BOOLEAN — marks onboarding seed entries, defaults false.
  - `created_at` TIMESTAMPTZ — defaults to now.
2. Security
- Enable RLS on daily_logs.
- Owner-scoped CRUD: each authenticated user can only SELECT/INSERT/UPDATE/DELETE their own rows (4 separate policies).
- `user_id` defaults to `auth.uid()` so client inserts that omit it still satisfy the INSERT WITH CHECK.
3. Indexes
- Index on (user_id, date) for fast per-user date queries.
*/

CREATE TABLE IF NOT EXISTS daily_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  date DATE NOT NULL,
  sleep NUMERIC(3,1) CHECK (sleep >= 0 AND sleep <= 12),
  stress NUMERIC(3,1) CHECK (stress >= 0 AND stress <= 10),
  mood NUMERIC(3,1) CHECK (mood >= 0 AND mood <= 10),
  trigger_category TEXT CHECK (trigger_category IN ('Work', 'Family', 'Health', 'Finance', 'None')),
  is_baseline BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE daily_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "select_own_logs" ON daily_logs;
CREATE POLICY "select_own_logs" ON daily_logs FOR SELECT
  TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "insert_own_logs" ON daily_logs;
CREATE POLICY "insert_own_logs" ON daily_logs FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "update_own_logs" ON daily_logs;
CREATE POLICY "update_own_logs" ON daily_logs FOR UPDATE
  TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_logs" ON daily_logs;
CREATE POLICY "delete_own_logs" ON daily_logs FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

CREATE INDEX IF NOT EXISTS idx_daily_logs_user_date ON daily_logs (user_id, date);
